"""Catalog status: every hypothesis, its route, its counts, what closed it.

    python -m futuresres.reporting.catalog_status

Everything here is derived at run time from `hypotheses.yaml`, the detectability gate, the
measured firing rates and the per-hypothesis cell files. Nothing is transcribed by hand,
because a status report that drifts from the artifacts it summarises is worse than none.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Final

import numpy as np
import yaml

from futuresres.reporting.detectability import (
    SCAN_POSITIONS,
    SCAN_POSITIONS_DISJOINT,
    assess,
    load_cells,
    sessions_and_bars,
)
from futuresres.stats.dsr import expected_max_sharpe

ROOT: Final[Path] = Path(__file__).resolve().parents[3]
REPORTS: Final[Path] = ROOT / "reports"
REGISTRY: Final[Path] = ROOT / "hypotheses.yaml"
REPORT: Final[Path] = REPORTS / "catalog_status.md"

#: Cell files that exist, and what each is known to be MISSING. F03's report covers both
#: instruments but its cell file holds only MNQ's 117, so 117 MGC trials were spent and not
#: persisted. That gap is carried into N explicitly rather than silently understating it.
KNOWN_UNPERSISTED: Final[dict[str, tuple[int, str]]] = {
    "F03": (117, "MGC's 117 cells were run and reported but never written to "
                 "reports/f03_cells.json"),
}


def trial_counts() -> tuple[dict[str, int], list[float], int]:
    counts: dict[str, int] = {}
    sharpes: list[float] = []
    unpersisted = 0
    for path in sorted(REPORTS.glob("f*_cells.json")):
        hid = path.stem.split("_")[0].upper()
        rows = json.loads(path.read_text(encoding="utf-8"))
        counts[hid] = len(rows)
        sharpes += [r["sharpe"] for r in rows if r.get("sharpe") is not None]
    for hid, (extra, _) in KNOWN_UNPERSISTED.items():
        if hid in counts:
            counts[hid] += extra
            unpersisted += extra
    return counts, sharpes, unpersisted


def render() -> str:
    registry = yaml.safe_load(REGISTRY.read_text(encoding="utf-8"))
    reg = {e["id"]: e for e in registry}
    cells = load_cells()
    session_counts = {p: sessions_and_bars(p)[0] for p in ("MNQ", "MGC")}
    verdicts: dict[str, list] = {}
    for entry in registry:
        if entry["status"] == "excluded":
            continue
        verdicts[entry["id"]] = assess(entry, cells, session_counts)

    counts, sharpes, unpersisted = trial_counts()
    n_trials = sum(counts.values())
    variance = float(np.var(sharpes, ddof=1)) if len(sharpes) > 1 else 0.0
    sr_star = expected_max_sharpe(n_trials, variance) if n_trials > 1 else 0.0

    w: list[str] = []
    a = w.append
    a("# Catalog status")
    a("")
    a("Generated by `python -m futuresres.reporting.catalog_status`. Derived at run time "
      "from `hypotheses.yaml`, the detectability gate, `reports/firing_rates.json` and the "
      "per-hypothesis cell files — nothing here is transcribed by hand.")
    a("")

    # ------------------------------------------------------------------ headline
    resolved = [e for e in registry if e["status"] not in ("untested",)]
    untested = [e for e in registry if e["status"] == "untested"]
    a("## Where the catalog stands")
    a("")
    a(f"**{len(registry)} hypotheses registered. {len(untested)} still testable. "
      f"0 promoted.**")
    a("")
    a("| status | count | meaning |")
    a("|---|---|---|")
    order = ["untested", "retired", "stage1_uninformative",
             "blocked_insufficient_events", "excluded"]
    meaning = {
        "untested": "not yet run",
        "retired": "run, and the evidence closed it",
        "stage1_uninformative": "run, but no sample could carry a verdict",
        "blocked_insufficient_events": "never run — arithmetic closed every route first",
        "excluded": "not registered for testing",
    }
    for st in order:
        n = sum(1 for e in registry if e["status"] == st)
        if n:
            a(f"| `{st}` | {n} | {meaning[st]} |")
    a("")
    a("**Three of the four closures were decided by arithmetic rather than by evidence.** "
      "Only F03 and F04 were closed by a result; F01 never ran, and F07 ran but could not "
      "inform. That ratio is the honest summary of this catalog so far: the binding "
      "constraint has been event scarcity, not the absence of signal — and those are "
      "different findings that a results table would render identically.")
    a("")

    # ------------------------------------------------------------------ N and SR*
    a("## Trial cost")
    a("")
    a("| | |")
    a("|---|---|")
    a(f"| **N (trials spent)** | **{n_trials}** |")
    a(f"| variance of trial Sharpes, V | {variance:.6f} |")
    a(f"| **expected max Sharpe under the null, SR\\*** | **{sr_star:.4f}** |")
    a("")
    a("| hypothesis | trials |")
    a("|---|---|")
    for hid in sorted(counts):
        note = ""
        if hid in KNOWN_UNPERSISTED:
            note = f" (incl. {KNOWN_UNPERSISTED[hid][0]} not persisted)"
        a(f"| {hid} | {counts[hid]}{note} |")
    a("")
    a("SR\\* is the Sharpe the best of N random trials would be expected to reach by chance. "
      f"Any candidate must clear **{sr_star:.4f}** before its Sharpe means anything, and "
      "that bar rises with every trial spent — including the 72 spent on F07, which could "
      "not have produced evidence.")
    a("")
    if unpersisted:
        a(f"> **Integrity gap: {unpersisted} trials are counted from a report rather than "
          f"from a cell file.** {KNOWN_UNPERSISTED['F03'][1]}. Worse, **`trials.jsonl` was "
          f"never written at all**: `src/futuresres/stats/trials.py` — the hash-chained "
          f"append-only log — was ported from the crypto repo with its tests, but no Stage 1 "
          f"runner calls it. N above is reconstructed from output files, which is exactly "
          f"the reconstruction the append-only log exists to make unnecessary. Every future "
          f"Stage 1 run must write to it.")
        a("")

    # ------------------------------------------------------------------ per hypothesis
    a("## Every hypothesis")
    a("")
    a("`per-cell` is the count one Stage 1 cell sees; `aggregate` pools the scanned "
      "positions and is available only when they are disjoint in time. Both are compared "
      "against the smallest sample at which a detection floor ever resolved.")
    a("")
    a("| id | name | status | per-cell route | aggregate route | closed by | trials |")
    a("|---|---|---|---|---|---|---|")
    for entry in registry:
        hid = entry["id"]
        vs = verdicts.get(hid, [])
        pos = SCAN_POSITIONS.get(hid, 1)
        dj = SCAN_POSITIONS_DISJOINT.get(hid, True)
        if not vs:
            cell_route = agg_route = "—"
        else:
            openc = [v for v in vs if not v.blocked]
            if vs[0].status == "FIRING RATE UNMEASURED":
                cell_route = "rate unmeasured"
            elif openc:
                cell_route = f"**open** {len(openc)}/{len(vs)}"
            else:
                cell_route = "closed"
            if pos == 1:
                agg_route = "n/a"
            elif not dj:
                agg_route = "**closed** (overlap)"
            else:
                ok = [v for v in vs if v.aggregate_ceiling
                      and (c := cells.get((v.product, v.proxy_horizon)))
                      and c.ever_resolved
                      and min(v.aggregate_ceiling, v.data_ceiling)
                      >= (c.smallest_resolving_n or 0)]
                agg_route = f"**open** {len(ok)}/{len(vs)}" if ok else "closed"
        closed_by = {
            "retired": "evidence",
            "stage1_uninformative": "sample — ran, could not inform",
            "blocked_insufficient_events": "arithmetic — never ran",
            "excluded": "registration",
            "untested": "—",
        }[entry["status"]]
        a(f"| {hid} | {entry['name']} | `{entry['status']}` | {cell_route} | {agg_route} | "
          f"{closed_by} | {counts.get(hid, 0)} |")
    a("")

    # ------------------------------------------------------------------ counts detail
    a("## Counts against the swept range")
    a("")
    a("| id | product | horizon | per-cell | aggregate | needs | status |")
    a("|---|---|---|---|---|---|---|")
    for hid in sorted(verdicts):
        for v in sorted(verdicts[hid], key=lambda v: (v.product, v.horizon)):
            c = cells.get((v.product, v.proxy_horizon))
            need = c.smallest_resolving_n if c and c.ever_resolved else None
            agg = (min(v.aggregate_ceiling, v.data_ceiling)
                   if v.aggregate_ceiling else None)
            a(f"| {hid} | {v.product} | {v.horizon}m | {v.effective:,} | "
              + (f"{agg:,}" if agg else "—") + " | "
              + (f"{need:,}" if need else "—") + f" | {v.status} |")
    a("")

    # ------------------------------------------------------------------ what remains
    a("## What remains testable, and by which route")
    a("")
    strong: list[str] = []
    weak: list[str] = []
    for hid, vs in verdicts.items():
        if reg[hid]["status"] != "untested":
            continue
        for v in vs:
            if v.blocked:
                continue
            (strong if v.product == "MNQ" else weak).append(
                f"{hid} {v.product} {v.horizon}m")
    a("**Strong-form routes** — MNQ, 99.13% coverage, no standing caveat:")
    a("")
    for s in sorted(strong):
        a(f"- {s}")
    a("")
    a("**Weak-form routes** — MGC, 70.47% coverage. Forward-filling thins measured "
      "volatility and biases toward apparent significance, so a null here is weaker "
      "evidence than the same null on MNQ:")
    a("")
    for s in sorted(weak):
        a(f"- {s}")
    a("")
    a("Plus the disjoint **aggregate** routes on F02, F03 and F04, which pool scanned "
      "positions and are the only way a scan carries a verdict once its cells are "
      "individually underpowered.")
    a("")
    a("**Nothing in the catalog has been promoted, and no Stage 1 has been run since the "
      "gate was corrected.** F03's and F04's verdicts predate the correction and were "
      "re-checked against it: F03's 13 slots are genuinely disjoint and its aggregate "
      "refutation stands; F04's per-cell base narrowed to MGC 120m and its best-cell "
      "figure was withdrawn and replaced. Neither verdict reversed.")
    a("")
    return "\n".join(w)


def main(argv: list[str] | None = None) -> int:
    argparse.ArgumentParser(prog="futuresres.reporting.catalog_status").parse_args(argv)
    REPORT.write_text(render(), encoding="utf-8")
    print(f"wrote {REPORT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
